=== floratos-lab/geworkbench-web/src/main/resources/plugins.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="plugins">
    <xs:annotation>
      <xs:documentation>Schema for geworkbench web plug-ins configuration</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:all>
        <xs:element name="analysis">
          <xs:annotation>
            <xs:documentation>analysis plug-ins</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element name="inputType" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="plugin" type="PluginType" maxOccurs="unbounded" minOccurs="0" />
                  </xs:sequence>
                  <xs:attribute type="xs:string" name="className" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="visualizer">
          <xs:annotation>
            <xs:documentation>visualizer plug-ins</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element name="inputType" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="plugin" type="PluginType" />
                  </xs:sequence>
                  <xs:attribute type="xs:string" name="className" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:all>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="PluginType">
	<xs:all>
		<xs:element type="xs:string" name="name" />
		<xs:element type="xs:string" name="description" />
		<xs:element type="xs:string" name="uiClass" />
	</xs:all>
  </xs:complexType>
</xs:schema>

=== floratos-lab/geworkbench-web/src/main/resources/plugins.xml
<?xml version="1.0" encoding="UTF-8"?>
<plugins xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="plugins.xsd">

	<!-- analysis and visualizer are separated because they are currently implemented 
		and used in different ways. -->
	<analysis>
	<inputType className="">
		<!-- These analysis plug-ins are called 'stand-alone', which really means they don't take any input data types -->
		<plugin>
			<name>LINCS</name>
			<description>
				The LINCS tool provides for query and display of data generated by the 
				Columbia LINCS Technology U01 and Computation U01 Centers, both under 
				the direction of Dr. Andrea Califano. It provides experimental drug-drug 
				synergy results, as well as computationally-derived similarity scores 
				for drug mode of action.  The NIH LINCS (Library of Integrated 
				Network-based Cellular Signatures) Program supports a 
				cellular-network-based investigation into biology at a number of centers 
				across the country. It catalogs changes to gene expression and other 
				cellular processes resulting from perturbation experiments.&gt;br/&gt;
				Data is preliminary, please see "
				&lt;a href='http://wiki.c2b2.columbia.edu/workbench/index.php/LINCS_Query#Currently_Available_Data' target='_blank'&gt;
				here&lt;/a&gt; 
				for currently available data.
			</description>
			<uiClass>org.geworkbenchweb.plugins.lincs.LINCS</uiClass>
		</plugin>
		<plugin>
			<name>Cellular Network Knowledge Base</name>
			<description>
				The Cellular Networks Knowledge Base (CNKB) is a repository of molecular interactions,
				including ones both computationally and experimentally derived. Sources for interactions
				include both publicly available databases as well as reverse-engineered
				cellular context-specific regulatory interactomes developed in the lab of Dr. Andrea Califano at Columbia University.
				For parameter settings see the 
				&lt;a href="http://wiki.c2b2.columbia.edu/workbench/index.php/GeWorkbench-web/Cellular_Networks_KnowledgeBase" target="_blank"&gt;CNKB&lt;/a&gt;
				tutorial.
			</description>
			<uiClass>org.geworkbenchweb.plugins.cnkb.CNKBStandaloneUI</uiClass>
		</plugin>
	</inputType>
	
	<inputType className="org.geworkbenchweb.pojos.MicroarrayDataset">
		<plugin>
			<name>Gene Ontology</name>
			<description>
				 The Gene Ontology Enrichment component allows a list of e.g. differentially expressed genes to be characterized using the Gene Ontology terms annotated to them. It asks, whether for any particular GO term, the fraction of genes assigned to it in the "changed-gene" list is higher than expected by chance (is over-represented), relative to the fraction of genes assigned to that term in the reference set. The Gene Ontology analysis component in geWorkbench is built around the Ontologizer 2.0 software product from Peter Robinson's group at the Charite Medical Institute of the Humboldt University in Berlin. Please see the 
				 &lt;a href="http://wiki.c2b2.columbia.edu/workbench/index.php/GeWorkbench-web/Gene_Ontology" target="_blank"&gt;Gene Ontology&lt;/a&gt;
				 tutorial for further details.
			</description>
			<uiClass>org.geworkbenchweb.plugins.geneontology.GOUI</uiClass>
		</plugin>
		
		<plugin>
			<name>ANOVA</name>
			<description>
				The geWorkbench ANOVA
				component implements a one-way analysis of variance calculation derived from TIGR's 
				&lt;a href="http://www.tm4.org/mev.html" target="_blank"&gt;MeV&lt;/a&gt;
				(MultiExperiment Viewer). At least three sets of
				arrays must be specified.  The ANOVA analysis returns any markers that
				show a significant expression difference across the array sets. 
				For parameter settings see the 
				&lt;a href="http://wiki.c2b2.columbia.edu/workbench/index.php/GeWorkbench-web/ANOVA" target="_blank"&gt;ANOVA&lt;/a&gt;
				tutorial.
			</description>
			<uiClass>org.geworkbenchweb.plugins.anova.AnovaUI</uiClass>
		</plugin>

		<plugin>
			<name>ARACNe</name>
			<description>
				ARACNe (Algorithm for the Reconstruction of Accurate Cellular Networks)
				(&lt;a href="http://www.ncbi.nlm.nih.gov/pubmed/15778709" target="_blank"&gt;Basso et al. 2005&lt;/a&gt;)
				is an information-theoretic algorithm used
				to identify transcriptional interactions between gene products using
				microarray gene expression profile data.
				Parameter settings see the
				&lt;a href="http://wiki.c2b2.columbia.edu/workbench/index.php/GeWorkbench-web/ARACNe" target="_blank"&gt;ARACNe&lt;/a&gt;
				tutorial).
			</description>
			<uiClass>org.geworkbenchweb.plugins.aracne.AracneUI</uiClass>
		</plugin>
		<plugin>
			<name>Cellular Network Knowledge Base</name>
			<description>
				The Cellular Networks Knowledge Base (CNKB) is a repository of molecular interactions,
				including ones both computationally and experimentally derived. Sources for interactions
				include both publicly available databases as well as reverse-engineered
				cellular context-specific regulatory interactomes developed in the lab of Dr. Andrea Califano at Columbia University.
				For parameter settings see the 
				&lt;a href="http://wiki.c2b2.columbia.edu/workbench/index.php/GeWorkbench-web/Cellular_Networks_KnowledgeBase" target="_blank"&gt;CNKB&lt;/a&gt;
				tutorial.
			</description>
			<uiClass>org.geworkbenchweb.plugins.cnkb.CNKBUI</uiClass>
		</plugin>
		<plugin>
			<name>Hierarchical Clustering</name>
			<description>
				Hierarchical Clustering   
				is a method to group arrays and/or markers together based on similarity on their expression profiles.
				geWorkbench implements its own code for agglomerative hierarchical clustering. Starting from individual points
				(the leaves of the tree), nearest neighbors are found for individual points, and then for groups of points,
				at each step building up a branched structure that converges toward a root that contains all points.
				The resulting graph tends to group similar items together. Several options for clustering method and metric are provided.
				For parameter settings see the 
				&lt;a href="http://wiki.c2b2.columbia.edu/workbench/index.php/GeWorkbench-web/Hierarchical_Clustering" target="_blank"&gt;Hierarchical Clustering&lt;/a&gt;
				tutorial.
			</description>
			<uiClass>org.geworkbenchweb.plugins.hierarchicalclustering.HierarchicalClusteringUI</uiClass>
		</plugin>
		<plugin>
			<name>MARINa(msVIPER)</name>
			<description>
				The msViper implementation of MARINa (MAster Regulator INference algorithm) 
				(&lt;a href="http://www.ncbi.nlm.nih.gov/pubmed/19209726" target="_blank"&gt;Lim et al., 2009&lt;/a&gt;, 
				&lt;a href="http://www.ncbi.nlm.nih.gov/pubmed/20531406" target="_blank"&gt;Lefebvre  et al., 2010&lt;/a&gt;)
				calculates whether the regulon of a transcription factor (TF) is enriched for genes that are differentially
				expressed between two classes of microarrays. The expression of the regulon genes (targets of the TF) serves as a proxy for the activity of the TF itself.
				TFs that are found to be differentially active are candidate master regulators of the phenotypic difference represented in the dataset. The user must
				supply a transcriptional network (e.g. reverse-engineered using
				&lt;a href="http://wiki.c2b2.columbia.edu/workbench/index.php/GeWorkbench-web/ARACNe" target="_blank"&gt;ARACNe&lt;/a&gt;
				) and a gene expression dataset.
				Please see the 
				&lt;a href="http://wiki.c2b2.columbia.edu/workbench/index.php/GeWorkbench-web/msViper" target="_blank"&gt;msViper&lt;/a&gt;
				tutorial).
			</description>
			<uiClass>org.geworkbenchweb.plugins.msviper.MsViperUI</uiClass>
		</plugin>		
		<plugin>
			<name>Differential Expression (T-Test)</name>
			<description>
				A t-Test
				analysis can be used to identify markers with statistically
				significant differential expression between two sets of microarrays (e.g. representing two different treatments or phenotypes).
				For parameter settings see the 
				&lt;a href="http://wiki.c2b2.columbia.edu/workbench/index.php/GeWorkbench-web/T-Test" target="_blank"&gt;t-Test&lt;/a&gt;
				tutorial).
			</description>
			<uiClass>org.geworkbenchweb.plugins.ttest.TTestUI</uiClass>
		</plugin>
	</inputType>
	<inputType className="org.geworkbenchweb.pojos.PdbFileInfo">
		<plugin>
			<name>MarkUs</name>
			<description>
				MarkUs
				(&lt;a href="http://www.ncbi.nlm.nih.gov/pubmed?term=21672961" target="_blank"&gt;Fischer et al., 2011&lt;/a&gt;)
				is a web server which runs a variety of analyses to characterize the biochemical function of a provided protein structure.
				MarkUs identifies related protein structures and sequences, detects protein cavities, and calculates the surface electrostatic
				potentials and amino acid conservation profile.
				Parameter settings are identical to those used in the desktop version of the analysis (see the
				&lt;a href="http://wiki.c2b2.columbia.edu/workbench/index.php/GeWorkbench-web/MarkUs" target="_blank"&gt;MarkUs&lt;/a&gt;
				tutorial).
			</description>
			<uiClass>org.geworkbenchweb.plugins.markus.MarkUsUI</uiClass>
		</plugin>
	</inputType>
	</analysis>

	<visualizer>
	<inputType className="org.geworkbenchweb.pojos.GOResult">
	<plugin>
		<name>GO Result Viewer</name>
		<description>
			Gene Ontology Result Viewer.
		</description>
		<uiClass>org.geworkbenchweb.plugins.geneontology.GOResultUI</uiClass>
	</plugin>
	</inputType>
	<inputType className="org.geworkbenchweb.pojos.PdbFileInfo">
	<plugin>
		<name>PDB File Viewer</name>
		<description>
			The PDB File Viewer provides a simple text viewer for PDB protein structure files.
		</description>
		<uiClass>org.geworkbenchweb.plugins.proteinstructure.SimplePDBViewer</uiClass>
	</plugin>
	<plugin>
		<name>Molecular Structure Viewer</name>
		<description>
